/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tic_tactoe;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class TIC_TACTOE extends javax.swing.JFrame {
private String startGame="X";
private int xCounter =0;
private int oCounter =0;
/**
* Creates new form TicTacToe
*/
public TIC_TACTOE() {
initComponents();
setSize(1200,600);
setLocationRelativeTo(null);
gameScore();
}
private void gameScore()
{
jlblPlayerX.setText(String.valueOf(xCounter));
jlblPlayerO.setText(String.valueOf(oCounter));
}
private void ChooseAPlayer()
{
if (startGame.equalsIgnoreCase("X"))
{
startGame="O";
}
else
{
startGame="X";
}
}
private void winningGame()
{
    String b1 = jButton1.getText();
    String b2 = jButton1.getText();
    String b3 = jButton1.getText();
    
    String b4 = jButton4.getText();
    String b5 = jButton5.getText();
    String b6 = jButton6.getText();
    
    String b7 = jButton7.getText();
    String b8 = jButton8.getText();
    String b9 = jButton9.getText();
      if (b1==("X") && b2 == ("X") && b3 == ("X"))
        {
            JOptionPane.showMessageDialog(this,"Player X Wins", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
            xCounter++;
            gameScore();
            jButton1.setBackground(Color.YELLOW);
            jButton2.setBackground(Color.YELLOW);
            jButton3.setBackground(Color.YELLOW);
        }
      if (b4==("X") && b5 == ("X") && b6 == ("X"))
        {
            JOptionPane.showMessageDialog(this,"Player X Wins", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
            xCounter++;
            gameScore();
            jButton4.setBackground(Color.RED);
            jButton5.setBackground(Color.RED);
            jButton6.setBackground(Color.RED);
        }
      if (b7==("X") && b8 == ("X") && b9 == ("X"))
        {
            JOptionPane.showMessageDialog(this,"Player X Wins", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
            xCounter++;
            gameScore();
            jButton7.setBackground(Color.GREEN);
            jButton8.setBackground(Color.GREEN);
            jButton9.setBackground(Color.GREEN);
        }
      if (b1==("X") && b4 == ("X") && b7 == ("X"))
        {
            JOptionPane.showMessageDialog(this,"Player X Wins", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
            xCounter++;
            gameScore();
            jButton1.setBackground(Color.YELLOW);
            jButton4.setBackground(Color.YELLOW);
            jButton7.setBackground(Color.YELLOW);
        }
      if (b2==("X") && b5 == ("X") && b8 == ("X"))
        {
            JOptionPane.showMessageDialog(this,"Player X Wins", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
            xCounter++;
            gameScore();
            jButton2.setBackground(Color.RED);
            jButton5.setBackground(Color.RED);
            jButton8.setBackground(Color.RED);
        }
      if (b3==("X") && b6 == ("X") && b9 == ("X"))
        {
            JOptionPane.showMessageDialog(this,"Player X Wins", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
            xCounter++;
            gameScore();
            jButton3.setBackground(Color.GREEN);
            jButton5.setBackground(Color.GREEN);
            jButton9.setBackground(Color.GREEN);
        }
      if (b1==("X") && b5 == ("X") && b9 == ("X"))
        {
            JOptionPane.showMessageDialog(this,"Player X Wins", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
            xCounter++;
            gameScore();
            jButton1.setBackground(Color.YELLOW);
            jButton5.setBackground(Color.YELLOW);
            jButton9.setBackground(Color.YELLOW);
        }
      if (b3==("X") && b5 == ("X") && b7 == ("X"))
        {
            JOptionPane.showMessageDialog(this,"Player X Wins", "Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
            xCounter++;
            gameScore();
            jButton3.setBackground(Color.PINK);
            jButton5.setBackground(Color.PINK);
            jButton7.setBackground(Color.PINK);
        }
      
}
/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {
jPanel1 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
jPanel2 = new javax.swing.JPanel();
jPanel3 = new javax.swing.JPanel();
jButton1 = new javax.swing.JButton();
jPanel4 = new javax.swing.JPanel();
jButton2 = new javax.swing.JButton();
jPanel5 = new javax.swing.JPanel();
jButton3 = new javax.swing.JButton();
jPanel6 = new javax.swing.JPanel();
jLabel2 = new javax.swing.JLabel();
jPanel7 = new javax.swing.JPanel();
jlblPlayerX = new javax.swing.JLabel();
jPanel8 = new javax.swing.JPanel();
jButton4 = new javax.swing.JButton();
jPanel9 = new javax.swing.JPanel();
jButton5 = new javax.swing.JButton();
jPanel10 = new javax.swing.JPanel();
jButton6 = new javax.swing.JButton();
jPanel11 = new javax.swing.JPanel();
jLabel3 = new javax.swing.JLabel();
jPanel12 = new javax.swing.JPanel();
jlblPlayerO = new javax.swing.JLabel();
jPanel13 = new javax.swing.JPanel();
jButton7 = new javax.swing.JButton();
jPanel14 = new javax.swing.JPanel();
jButton8 = new javax.swing.JButton();
jPanel16 = new javax.swing.JPanel();
jButton9 = new javax.swing.JButton();
jPanel15 = new javax.swing.JPanel();
jbtnReset = new javax.swing.JButton();
jPanel17 = new javax.swing.JPanel();
jbtnExit = new javax.swing.JButton();
setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setTitle("Tic Tac Toe Games");
jPanel1.setBackground(new java.awt.Color(153, 153, 153));
jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
jPanel1.setLayout(new java.awt.BorderLayout());
jLabel1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel1.setText("Tic Tac Toe");
jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);
jPanel2.setBackground(new java.awt.Color(102, 102, 102));
jPanel2.setLayout(new java.awt.GridLayout(3, 5, 2, 2));
jPanel3.setLayout(new java.awt.BorderLayout());
jButton1.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});
jPanel3.add(jButton1, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel3);
jPanel4.setLayout(new java.awt.BorderLayout());
jButton2.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});
jPanel4.add(jButton2, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel4);
jPanel5.setLayout(new java.awt.BorderLayout());
jButton3.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jButton3.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton3ActionPerformed(evt);
}
});
jPanel5.add(jButton3, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel5);
jPanel6.setLayout(new java.awt.BorderLayout());
jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
jLabel2.setText("Player X:");
jPanel6.add(jLabel2, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel6);
jPanel7.setLayout(new java.awt.BorderLayout());
jlblPlayerX.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
jlblPlayerX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jlblPlayerX.setText("jLabel4");
jPanel7.add(jlblPlayerX, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel7);
jPanel8.setLayout(new java.awt.BorderLayout());
jButton4.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jPanel8.add(jButton4, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel8);
jPanel9.setLayout(new java.awt.BorderLayout());
jButton5.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jPanel9.add(jButton5, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel9);
jPanel10.setLayout(new java.awt.BorderLayout());
jButton6.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jPanel10.add(jButton6, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel10);
jPanel11.setLayout(new java.awt.BorderLayout());
jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
jLabel3.setText("Player O:");
jPanel11.add(jLabel3, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel11);
jPanel12.setLayout(new java.awt.BorderLayout());
jlblPlayerO.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
jlblPlayerO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jlblPlayerO.setText("jLabel5");
jPanel12.add(jlblPlayerO, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel12);
jPanel13.setLayout(new java.awt.BorderLayout());
jButton7.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jPanel13.add(jButton7, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel13);
jPanel14.setLayout(new java.awt.BorderLayout());
jButton8.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jPanel14.add(jButton8, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel14);
jPanel16.setLayout(new java.awt.BorderLayout());
jButton9.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
jPanel16.add(jButton9, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel16);
jPanel15.setLayout(new java.awt.BorderLayout());
jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
jbtnReset.setText("Reset");
jPanel15.add(jbtnReset, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel15);
jPanel17.setLayout(new java.awt.BorderLayout());
jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
jbtnExit.setText("Exit");
jbtnExit.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jbtnExitActionPerformed(evt);
}
});
jPanel17.add(jbtnExit, java.awt.BorderLayout.CENTER);
jPanel2.add(jPanel17);
jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);
getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
pack();
}// </editor-fold>//GEN-END:initComponents
private JFrame frame;
private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
// Exit
frame = new JFrame("Exit");
if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Tic Tac Toe",
JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_NO_OPTION){
System.exit(0);
}
}//GEN-LAST:event_jbtnExitActionPerformed
private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
    jButton1.setText(null);
    jButton1.setText(null);
    jButton1.setText(null);
    
    jButton4.setText(null);
    jButton5.setText(null);
    jButton6.setText(null);
    
    jButton7.setText(null);
    jButton8.setText(null);
    jButton9.setText(null);
}
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jButton1.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton1.setForeground(Color.green);
}
else
{
jButton1.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}//GEN-LAST:event_jButton1ActionPerformed
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jButton2.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton2.setForeground(Color.GREEN);
}
else
{
jButton2.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}//GEN-LAST:event_jButton2ActionPerformed
private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jButton3.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton3.setForeground(Color.green);
}
else
{
jButton3.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}
private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jButton4.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton4.setForeground(Color.green);
}
else
{
jButton4.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}//GEN-LAST:event_jButton1ActionPerformed
private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jButton5.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton5.setForeground(Color.GREEN);
}
else
{
jButton5.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}//GEN-LAST:event_jButton2ActionPerformed
private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jButton6.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton6.setForeground(Color.green);
}
else
{
jButton6.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}
private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jButton7.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton7.setForeground(Color.green);
}
else
{
jButton7.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}//GEN-LAST:event_jButton1ActionPerformed
private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jButton2.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton8.setForeground(Color.GREEN);
}
else
{
jButton8.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}//GEN-LAST:event_jButton2ActionPerformed
private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jButton9.setText(startGame);
if (startGame.equalsIgnoreCase("X"))
{
jButton9.setForeground(Color.green);
}
else
{
jButton9.setForeground(Color.blue);
}
ChooseAPlayer();
winningGame();
}
//GEN-LAST:event_jButton3ActionPerformed
/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(TIC_TACTOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(TIC_TACTOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(TIC_TACTOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(TIC_TACTOE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>
/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new TIC_TACTOE().setVisible(true);
}
});
}
// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JButton jButton3;
private javax.swing.JButton jButton4;
private javax.swing.JButton jButton5;
private javax.swing.JButton jButton6;
private javax.swing.JButton jButton7;
private javax.swing.JButton jButton8;
private javax.swing.JButton jButton9;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JPanel jPanel1;
private javax.swing.JPanel jPanel10;
private javax.swing.JPanel jPanel11;
private javax.swing.JPanel jPanel12;
private javax.swing.JPanel jPanel13;
private javax.swing.JPanel jPanel14;
private javax.swing.JPanel jPanel15;
private javax.swing.JPanel jPanel16;
private javax.swing.JPanel jPanel17;
private javax.swing.JPanel jPanel2;
private javax.swing.JPanel jPanel3;
private javax.swing.JPanel jPanel4;
private javax.swing.JPanel jPanel5;
private javax.swing.JPanel jPanel6;
private javax.swing.JPanel jPanel7;
private javax.swing.JPanel jPanel8;
private javax.swing.JPanel jPanel9;
private javax.swing.JButton jbtnExit;
private javax.swing.JButton jbtnReset;
private javax.swing.JLabel jlblPlayerO;
private javax.swing.JLabel jlblPlayerX;
// End of variables declaration//GEN-END:variables
}
    
